---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: server-bot
  name: server-bot-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: server-bot-app
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: server-bot-app
    spec:
      containers:
        - name: server-bot-app
          image: jpbarto/server-bot:v2
          env:
            - name: BOT_VERSION
              value: 'v1.0.2'
          ports:
            - containerPort: 5000
              name: server-bot-port

