---
apiVersion: v1
kind: Service
metadata:
  namespace: server-bot
  name: server-bot-service
spec:
  selector:
    app.kubernetes.io/name: server-bot-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: server-bot-port
