name: Enforce change window

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    paths:
      - 'block-1/*'
      - 'block-2/*'

jobs:
  Audit-Pull-Request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const requiredLabels = ['no release notes', 'public release notes'];
            let labels = [];

            if (context.payload.pull_request) {
              labels = context.payload.pull_request.labels;
            } else if (context.payload.issue) {
              labels = context.payload.issue.labels;
            }

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'This has been blocked by GH Actions'
            })

            if (labels.filter(l => requiredLabels.includes(l.name)).length === 0) {
              throw new Error(`Required labels: ${requiredLabels.join(', ')}`);
            }
