name: Enforce change freeze

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    paths:
      - 'block-1/*'
      - 'block-2/*'

jobs:
  Audit-Pull-Request:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log (context)

            var startTime = '09:00:10';
            var endTime = '19:00:00';

            currentDate = new Date()

            startDate = new Date(currentDate.getTime());
            startDate.setHours(startTime.split(":")[0]);
            startDate.setMinutes(startTime.split(":")[1]);
            startDate.setSeconds(startTime.split(":")[2]);

            endDate = new Date(currentDate.getTime());
            endDate.setHours(endTime.split(":")[0]);
            endDate.setMinutes(endTime.split(":")[1]);
            endDate.setSeconds(endTime.split(":")[2]);

            freezeFlag = startDate < currentDate && endDate > currentDate

            if (! freezeFlag) {
              return 'pass'
            }

            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['ChangeFreeze']
            })

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'This has been blocked by GH Actions'
            })

            throw new Error(`PR stopped due to change freeze ${startDate}`);
